#!/bin/sh

# ステージに追加されたファイルのみをフォーマット
FILES=$(git diff --cached --name-only --diff-filter=ACM)
if [ -n "$FILES" ]; then
  echo "Formatting staged files..."
  # フォーマット対象外のファイルでエラーになったとしても無視
  yarn prettier --write $FILES || true
  git add $FILES
fi
